CREATE TABLE IF NOT EXISTS sales (
    id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    store_name VARCHAR(100) NOT NULL,
    sales_value NUMERIC(12,2) NOT NULL
);

INSERT INTO sales (product_name, store_name, sales_value) VALUES
('Laptop Pro X15', 'Tech Central Downtown', 1599.99),
('Smartphone Alpha 8', 'Tech Central Downtown', 749.50),
('Wireless Earbuds Z', 'Tech Central Downtown', 99.00),
('4K Monitor M27', 'Tech Central Downtown', 349.99),
('Mechanical Keyboard R', 'Tech Central Downtown', 125.75),
('Laptop Pro X15', 'Electro Mart West', 1605.00),
('Smartphone Alpha 8', 'Electro Mart West', 750.25),
('Gaming Mouse G5', 'Electro Mart West', 65.99),
('External SSD 1TB', 'Electro Mart West', 149.00),
('Smart Watch Series 5', 'Electro Mart West', 299.99),
('Espresso Machine E6', 'Home Goods North', 450.00),
('Blender PowerMix 3000', 'Home Goods North', 79.99),
('Toaster Oven T4', 'Home Goods North', 45.50),
('Robot Vacuum V8', 'Home Goods North', 320.00),
('Air Fryer AF-90', 'Home Goods North', 89.95),
('Espresso Machine E6', 'Kitchen World South', 445.50),
('Stand Mixer KM-Pro', 'Kitchen World South', 219.00),
('Induction Cooktop IC1', 'Kitchen World South', 189.99),
('Pressure Cooker PCL', 'Kitchen World South', 59.90),
('Hand Mixer HMX-2', 'Kitchen World South', 29.50),
('T-Shirt Cotton Basic', 'Apparel Outlet', 15.00),
('Jeans Slim Fit', 'Apparel Outlet', 59.99),
('Sneakers Runner X', 'Apparel Outlet', 75.00),
('Jacket Winter Puffer', 'Apparel Outlet', 120.50),
('Socks Pack 6', 'Apparel Outlet', 9.99),
('Running Shoes Aero 7', 'Sports Gear Depot', 85.50),
('Yoga Mat Deluxe', 'Sports Gear Depot', 35.00),
('Dumbbell Set 20kg', 'Sports Gear Depot', 69.99),
('Resistance Band Kit', 'Sports Gear Depot', 19.99),
('Protein Powder WPC', 'Sports Gear Depot', 45.00),
('Novel Sci-Fi Classic', 'Book Nook', 12.99),
('Journal Leather Bound', 'Book Nook', 25.00),
('Pen Set Premium', 'Book Nook', 18.50),
('Kids Book Adventures', 'Book Nook', 8.99),
('Magazine Monthly Tech', 'Book Nook', 7.50),
('Sofa Sectional L-Shape', 'Furniture Mega', 980.00),
('Coffee Table Oak', 'Furniture Mega', 150.00),
('Desk Office Modern', 'Furniture Mega', 299.99),
('Dining Chair Set 4', 'Furniture Mega', 199.00),
('Lamp Floor LED', 'Furniture Mega', 75.00),
('Laptop Pro X15', 'Tech Central East', 1580.00),
('Smartphone Alpha 8', 'Tech Central East', 745.00),
('Wireless Earbuds Z', 'Tech Central East', 98.50),
('4K Monitor M27', 'Tech Central East', 355.00),
('Mechanical Keyboard R', 'Tech Central East', 120.00),
('Espresso Machine E6', 'Home Goods West', 460.00),
('Blender PowerMix 3000', 'Home Goods West', 85.00),
('Toaster Oven T4', 'Home Goods West', 44.99);